# Generated by Django 4.2.11 on 2024-11-04 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_location_socialmedia_alter_business_location_and_more'),
        ('order', '0002_alter_order_location'),
        ('profiles', '0002_remove_profile_location_remove_profile_social_media'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
