# Generated by Django 4.2.11 on 2025-03-25 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_location'),
        ('profiles', '0006_remove_profile_location_remove_profile_social_media'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
    ]
