services:     
  errandhelper-backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: errandhelper-backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - django_network

  db:
    image: postgres:17
    container_name: errandhelper-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=errandhelper
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Qwerty@123
    ports:
      - "5432:5432"
    networks:
      - django_network

volumes:
  postgres_data:

networks:
  django_network:
    driver: bridge