# Generated by Django 4.2.11 on 2025-03-28 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_alter_business_options_remove_business_location_and_more'),
        ('media_location', '0001_initial'),
        ('business_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='business',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to='business.business'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to='media_location.location'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='social_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to='media_location.socialmedia'),
        ),
    ]
