# Generated by Django 4.2.11 on 2024-11-02 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessCategory',
        ),
    ]
