# Generated by Django 4.2.11 on 2024-11-15 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_delete_businesscategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
