# Generated by Django 4.2.11 on 2025-08-15 11:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_add_missing_name_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200)),
                ('town', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='operating_hours',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='portfolio_images',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='price_range',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='services_offered',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='social_links',
        ),
    ]
