# Generated by Django 4.2.11 on 2025-08-15 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_category_location_service_and_more'),
        ('business', '0002_badge_businessinfo_socialmedia_remove_business_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='business_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to='business.businessinfo'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='authentication.category'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='services',
            field=models.ManyToManyField(blank=True, to='authentication.service'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to='authentication.location'),
        ),
    ]
