# Generated by Django 4.2.11 on 2025-08-15 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_businessprofile_business_info_service_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessProfile',
        ),
    ]
