# Generated by Django 4.2.11 on 2025-08-16 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_delete_businessprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
