# Generated by Django 4.2.11 on 2025-09-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_service_category_delete_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('business', 'Business')], max_length=10, default='client'),
        ),
    ]
