# Generated by Django 4.2.11 on 2025-09-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20250926_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('business', 'Business')], max_length=10),
        ),
    ]
