# Generated by Django 4.2.11 on 2025-10-12 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_username_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientProfile',
        ),
    ]
