# Generated by Django 4.2.11 on 2025-10-12 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_errand_location_errand_locations'),
        ('authentication', '0010_delete_clientprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
