# Generated by Django 4.2.11 on 2024-11-02 21:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_delete_businesscategory'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business')),
                ('category', models.ManyToManyField(related_name='business', to='service.category')),
            ],
        ),
    ]
