# Generated by Django 4.2.11 on 2025-08-15 11:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_badge_businessinfo_socialmedia_remove_business_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='BusinessCategory',
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS business_businessinfo CASCADE;",
            reverse_sql=""
        ),
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business_logos/')),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('business_email', models.CharField(blank=True, max_length=255)),
                ('business_phone', models.CharField(blank=True, max_length=255)),
                ('business_tagline', models.CharField(blank=True, max_length=255)),
                ('business_description', models.CharField(blank=True, max_length=255)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('badges', models.ManyToManyField(blank=True, to='business.badge')),
                ('social_links', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_info', to='business.socialmedia')),
            ],
            options={
                'verbose_name_plural': 'Business Information',
            },
        ),
    ]
