# Generated by Django 4.2.11 on 2024-11-03 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_businesscategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesscategory',
            old_name='category',
            new_name='categories',
        ),
    ]
