# Generated by Django 4.2.11 on 2025-08-15 12:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_delete_business_delete_businesscategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
