# Generated by Django 4.2.11 on 2024-11-03 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_location_remove_profile_social_media'),
        ('business', '0003_rename_category_businesscategory_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='profiles.location'),
        ),
        migrations.AddField(
            model_name='business',
            name='social_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='profiles.socialmedia'),
        ),
    ]
