# Generated by Django 4.2.11 on 2025-08-15 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0005_rename_logo_businessinfo_business_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessinfo',
            name='badges',
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
    ]
