# Generated by Django 4.2.11 on 2025-08-16 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_remove_businessinfo_badges_businessinfo_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='kra_pin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='license',
            field=models.FileField(blank=True, null=True, upload_to='business_docs/'),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='tax_compliance',
            field=models.FileField(blank=True, null=True, upload_to='business_docs/'),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='verification_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
