# Generated by Django 4.2.11 on 2025-08-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price_from',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='price_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='price_type',
            field=models.CharField(blank=True, choices=[('hourly', 'Hourly Rate'), ('fixed', 'Fixed Price'), ('quote', 'By Quote')], default='quote', max_length=10, null=True),
        ),
    ]
