# Generated by Django 4.2.11 on 2025-09-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_frequentlyaskedquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
