# Generated by Django 4.2.11 on 2025-09-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_businessinfo_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='business_logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/business_logos/'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='instagram',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='website',
            field=models.URLField(),
        ),
    ]
