# Generated by Django 4.2.11 on 2025-10-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_alter_businessinfo_business_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
