# Generated by Django 4.2.11 on 2025-10-12 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_errand_remove_instruction_order_and_more'),
        ('media_location', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
