# Generated by Django 4.2.11 on 2024-08-28 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('business', '0001_initial'),
        ('service', '0002_alter_service_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('stop_time', models.TimeField()),
                ('frequency', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(editable=False, max_length=15, unique=True)),
                ('completed', models.BooleanField()),
                ('accepted', models.BooleanField()),
                ('payment', models.PositiveIntegerField()),
                ('special_instructions', models.TextField()),
                ('paid', models.BooleanField()),
                ('order_status', models.CharField(choices=[('created', 'created'), ('accepted', 'accepted'), ('verified', 'verified'), ('complete', 'complete')], default='created', max_length=20)),
                ('activity_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.activitytime')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.location')),
                ('services', models.ManyToManyField(related_name='orders', to='service.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField()),
                ('instruction', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='order.order')),
            ],
        ),
    ]
