# Generated by Django 4.2.11 on 2025-08-15 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_delete_business_delete_businesscategory_and_more'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='order',
                    name='business',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.businessinfo'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    "ALTER TABLE order_order DROP CONSTRAINT IF EXISTS order_order_business_id_fkey;",
                    reverse_sql=""
                ),
                migrations.RunSQL(
                    "ALTER TABLE order_order ADD CONSTRAINT order_order_business_id_fkey FOREIGN KEY (business_id) REFERENCES business_businessinfo(id) ON DELETE CASCADE;",
                    reverse_sql=""
                ),
            ],
        ),
    ]
