# Generated by Django 4.2.11 on 2024-11-15 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_location_socialmedia_remove_profile_phone_number_and_more'),
        ('order', '0002_alter_order_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.location'),
        ),
    ]
