# Generated by Django 4.2.11 on 2025-10-12 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0010_delete_clientprofile'),
        ('order', '0002_alter_order_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='Errand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(editable=False, max_length=15, unique=True)),
                ('errand_title', models.CharField(max_length=255)),
                ('descriptions', models.JSONField(blank=True, default=list)),
                ('start_date', models.DateTimeField()),
                ('stop_date', models.DateTimeField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10)),
                ('budget_type', models.CharField(choices=[('fixed', 'Fixed'), ('hourly', 'Hourly')], default='fixed', max_length=10)),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('use_milestones', models.BooleanField(default=False)),
                ('payment_method', models.CharField(choices=[('card', 'Card'), ('cash', 'Cash'), ('platform', 'Platform')], max_length=20)),
                ('special_instructions', models.TextField(blank=True)),
                ('contact_preference', models.CharField(default='platform', max_length=50)),
                ('agree_terms', models.BooleanField(default=False)),
                ('agree_escrow', models.BooleanField(default=False)),
                ('services', models.JSONField(blank=True, default=list)),
                ('milestones', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(limit_choices_to={'role': 'business'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_errands', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_errands', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.location')),
            ],
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='activity_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='business',
        ),
        migrations.RemoveField(
            model_name='order',
            name='location',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='ActivityTime',
        ),
        migrations.DeleteModel(
            name='Instruction',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
