# Generated by Django 4.2.11 on 2025-10-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_location', '0003_location'),
        ('order', '0003_errand_remove_instruction_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errand',
            name='location',
        ),
        migrations.AddField(
            model_name='errand',
            name='locations',
            field=models.ManyToManyField(related_name='errands', to='media_location.location'),
        ),
    ]
