# Generated by Django 4.2.11 on 2025-03-25 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_location', '0001_initial'),
        ('order', '0003_alter_order_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_location.location'),
        ),
    ]
