# Generated by Django 4.2.11 on 2025-10-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_errand_location_errand_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errand',
            name='budget_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=255, null=True),
        ),
        migrations.AlterField(
            model_name='errand',
            name='budget_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('hourly', 'Hourly')], default='fixed', max_length=255),
        ),
        migrations.AlterField(
            model_name='errand',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=255),
        ),
    ]
