# Generated by Django 4.2.11 on 2025-10-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_errand_budget_amount_alter_errand_budget_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errand',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('cash', 'Cash'), ('platform', 'Platform')], max_length=100),
        ),
        migrations.AlterField(
            model_name='errand',
            name='reference_number',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
