# Generated by Django 4.2.11 on 2025-10-14 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_errand_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrandImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='errand_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('errand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='order.errand')),
            ],
        ),
    ]
