# Generated by Django 4.2.11 on 2025-10-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_errandimage'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE order_errandimage DROP COLUMN IF EXISTS image;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='errandimage',
                    name='image',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE order_errandimage ADD COLUMN IF NOT EXISTS image_url varchar(500);",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='errandimage',
                    name='image_url',
                    field=models.URLField(blank=True, max_length=500, null=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='errand',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('platform', 'Platform'), ('bank', 'Bank')], max_length=100),
        ),
    ]
