# Generated by Django 4.2.11 on 2025-11-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_alter_socialmedia_instagram_and_more'),
        ('order', '0008_remove_errandimage_image_errandimage_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errand',
            name='services',
        ),
        migrations.AddField(
            model_name='errand',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='errands', to='business.service'),
        ),
    ]
