# Generated by Django 4.2.11 on 2025-11-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_errand_services_errand_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errand',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
