# Generated by Django 4.2.11 on 2025-12-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_errand_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='errand',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='errand',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('platform', 'Platform'), ('mpesa', 'MPESA')], max_length=100),
        ),
    ]
