# Generated by Django 4.2.11 on 2026-01-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_mpesatransaction_wallet_alter_errand_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='errand',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending'), ('held', 'Held in Escrow'), ('released', 'Released'), ('refunded', 'Refunded')], default='unpaid', max_length=20),
        ),
    ]
