# Generated by Django 4.2.11 on 2026-01-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_mpesatransaction_checkout_request_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errand',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending'), ('held', 'Paid and Held'), ('released', 'Released'), ('refunded', 'Refunded'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='checkoutRequestID',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
