# Generated by Django 4.2.11 on 2026-01-16 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_errand_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpesatransaction',
            name='checkoutRequestID',
        ),
        migrations.RemoveField(
            model_name='mpesatransaction',
            name='merchantRequestID',
        ),
        migrations.RemoveField(
            model_name='mpesatransaction',
            name='mpesaReceiptNumber',
        ),
    ]
