# Generated by Django 4.2.11 on 2026-02-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0015_remove_mpesatransaction_checkoutrequestid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="errand",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
