name: Build and Publish image to Docker Hub

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  publish_images:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
      
    - name: Set version number
      run: echo "VERSION=v1.${{ github.run_number }}" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker build -t "${{secrets.IMAGE_NAME}}":latest .
    - name: push image to docker hub
      run: |
        echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
        docker push "${{secrets.IMAGE_NAME}}":latest
